(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["default~advanced-search-advanced-search-module~batch-precredit-add-batch-precredit-add-module~credit~15704ef9"],{

/***/ "./src/app/pages/tzb/custom/constant/custOperation.codeValue.ts":
/*!**********************************************************************!*\
  !*** ./src/app/pages/tzb/custom/constant/custOperation.codeValue.ts ***!
  \**********************************************************************/
/*! exports provided: CustDetialInfoList, InfoList, preAppprovedListinfo */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "CustDetialInfoList", function() { return CustDetialInfoList; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "InfoList", function() { return InfoList; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "preAppprovedListinfo", function() { return preAppprovedListinfo; });
//营销 目标客户探索-按分页查询出客户详细信息结果
var CustDetialInfoList = [
    { flag: 'CUST_ID', value: "CUST_ID", label: "客户号", orderCode: 8, isCheck: true, isDisabled: true, isDisabled1: true, property: "generalAttr" },
    { flag: 'CUST_NAME', value: "CUST_NAME", label: "客户名称", orderCode: 9, isCheck: true, isDisabled: true, isDisabled1: true, property: "generalAttr" },
    { flag: 'A', value: "", label: "存款类", orderCode: 157, isDisabled: true, isDisabled1: true, property: "saveAttr" },
    { flag: 'B', value: "", label: "贷款类", orderCode: 158, isDisabled: true, isDisabled1: true, property: "loansAttr" },
    { flag: 'C', value: "", label: "信用卡", orderCode: 159, isDisabled: true, isDisabled1: true, property: "creditAttr" },
    { flag: 'D', value: '', label: '承兑', orderCode: 53, isDisabled1: true, property: "acceptAttr" },
    { flag: 'E', value: "", label: "积分卡", orderCode: 56, isDisabled1: true, property: "pointAttr" },
    // {flag:'F', value: "", label: "网上银行", orderCode: 57, isDisabled1: true, property: "onlineAttr" },
    // {flag:'G', value: "", label: "微信银行", orderCode: 58, isDisabled1: true, property: "WX_Attr" },
    // {flag:'H', value: "", label: "手机银行", orderCode: 163, isDisabled1: true, property: "phoneAttr" },
    { flag: 'I', value: "", label: "FTP利润", orderCode: 167, isDisabled1: true, isCheck: true, property: "FTPAttr" },
    { flag: 'M_BEFORE_FTP', value: 'M_BEFORE_FTP', label: '本月折扣前利润', orderCode: 79, property: "FTPAttr" },
    { flag: 'LMM_BEFORE_FTP', value: 'LMM_BEFORE_FTP', label: '上月折扣前利润', orderCode: 80, property: "FTPAttr" },
    { flag: 'SIX_M_BEFORE_FTP', value: 'SIX_M_BEFORE_FTP', label: '前六月折扣前利润', orderCode: 81, property: "FTPAttr", },
    { flag: 'Y_BEFORE_FTP', value: 'Y_BEFORE_FTP', label: '本年折扣前利润', orderCode: 82, property: "FTPAttr" },
    { flag: 'LY_BEFORE_FTP', value: 'LY_BEFORE_FTP', label: '上年折扣前利润', orderCode: 83, isCheck: true, property: "FTPAttr" },
    { flag: 'M_AFTER_FTP', value: 'M_AFTER_FTP', label: '本月折扣后利润', orderCode: 84, property: "FTPAttr" },
    { flag: 'LM_AFTER_FTP', value: 'LM_AFTER_FTP', label: '上月折扣后利润', orderCode: 85, property: "FTPAttr" },
    { flag: 'SIXM_AFTER_FTP', value: 'SIXM_AFTER_FTP', label: '前六月折扣后利润', orderCode: 86, property: "FTPAttr", },
    { flag: 'Y_AFTER_FTP', value: 'Y_AFTER_FTP', label: '本年折扣后利润', orderCode: 87, property: "FTPAttr" },
    { flag: 'LY_AFTER_FTP', value: 'LY_AFTER_FTP', label: '上年折扣后利润', orderCode: 88, property: "FTPAttr" },
    { flag: 'DT', value: 'DT', label: '数据日期', orderCode: 148, code: 'order' },
    // {flag:'BELONG_ORG', value: 'BELONG_ORG', label: '主联系人机构', orderCode: 1, code: 'order', property: "generalAttr" },
    { flag: 'BELONG_ORG_NAME', value: "BELONG_ORG_NAME", label: "所属机构", orderCode: 3, code: 'order', property: "generalAttr" },
    { flag: 'PRINCIPAL_LINKMAN', value: "PRINCIPAL_LINKMAN", label: "主联系人", orderCode: 4, code: 'order', property: "generalAttr" },
    { flag: 'LINKMAN_NAME', value: "LINKMAN_NAME", label: "主联系人名称", orderCode: 5, code: 'order', property: "generalAttr" },
    { flag: 'TELLER_ID', value: "TELLER_ID", label: "协储员号", orderCode: 7, code: 'order', property: "generalAttr" },
    { flag: 'TELLER_NM', value: "TELLER_NM", label: "协储员名称", orderCode: 149, code: 'order', property: "generalAttr" },
    { flag: 'TELLER_ORG', value: "TELLER_ORG", label: "协储员所属机构", orderCode: 150, code: 'order', property: "generalAttr" },
    { flag: 'TELLER_ORG_NM', value: "TELLER_ORG_NM", label: "协储员所属机构名称", orderCode: 151, code: 'order', property: "generalAttr" },
    { flag: 'CUST_TYPE', value: "CUST_TYPE", label: "客户类型", orderCode: 10, code: 'order', property: "generalAttr" },
    { flag: 'CUST_ATTR', value: "CUST_ATTR", label: "客户属性", orderCode: 11, code: 'order', property: "generalAttr" },
    { flag: 'CREATE_TIME', value: "CREATE_TIME", label: "建立日期", orderCode: 12, code: 'order', },
    // {flag:'CYCLE', value: "CYCLE", label: "客户生命周期", orderCode: 13, code: 'order', },
    { flag: 'IS_AGRICULTURE', value: "IS_AGRICULTURE", label: "涉农属性", orderCode: 14, code: 'order', property: "generalAttr" },
    { flag: 'IDCARDTYPE', value: "IDCARDTYPE", label: "证件类型", orderCode: 15, code: 'order', property: "generalAttr" },
    { flag: 'IDCARDNO', value: "IDCARDNO", label: "证件号码", judgeGrop: "X_GPSH_M_P038_F164", judgeField: "X_MYSH_M_P024_F156", orderCode: 16, code: 'order', property: "generalAttr" },
    { flag: 'TEL', value: "TEL", label: "联系号码", judgeGrop: "X_GPSH_M_P038_F165", judgeField: "X_MYSH_M_P024_F157", orderCode: 17, code: 'order', property: "generalAttr" },
    { flag: 'SEXS', value: "SEXS", label: "性别", orderCode: 18, code: 'order', property: "presonAttr" },
    { flag: 'AGE', value: "AGE", label: "年龄", orderCode: 19, code: 'order', },
    { flag: 'RESIDTYPE', value: "RESIDTYPE", label: "户口性质", orderCode: 20, code: 'order', property: "presonAttr" },
    { flag: 'BIRTHDATE', value: "BIRTHDATE", label: "出生日期", orderCode: 21, code: 'order', property: "presonAttr" },
    { flag: 'MARITALSTATUS', value: "MARITALSTATUS", label: "婚姻状况", orderCode: 22, code: 'order', property: "presonAttr" },
    { flag: 'MONTHINCOME', value: "MONTHINCOME", label: "月收入", orderCode: 23, code: 'order', property: "presonAttr" },
    { flag: 'YEARINCOME', value: "YEARINCOME", label: "年收入", orderCode: 24, code: 'order', property: "presonAttr" },
    { flag: 'FAMILY_ADDR', value: "FAMILY_ADDR", label: "家庭地址", judgeGrop: "X_GPSH_M_P038_F166", judgeField: "X_MYSH_M_P024_F158", orderCode: 25, code: 'order', property: "presonAttr" },
    { flag: 'BUSADDRCODE', value: "BUSADDRCODE", label: "经营地址", judgeGrop: "X_GPSH_M_P038_F167", judgeField: "X_MYSH_M_P024_F159", orderCode: 26, code: 'order', property: "companyAttr" },
    { flag: 'PE_ASSET', value: "PE_ASSET", label: "资产总额", orderCode: 27, code: 'order', property: "companyAttr" },
    { flag: 'PE_DEBT', value: "PE_DEBT", label: "负债总额", orderCode: 28, code: 'order', property: "companyAttr" },
    // {flag:'INDUSTRY', value: "INDUSTRY", label: "所属行业", orderCode: 29, code: 'order', property: "companyAttr" },
    { flag: 'ENT_TYPE', value: "ENT_TYPE", label: "中小型企业类型", orderCode: 30, code: 'order', property: "companyAttr" },
    { flag: 'CORP_NAME', value: "CORP_NAME", label: "法人代表", orderCode: 31, code: 'order', property: "companyAttr" },
    { flag: 'CORP_MOBILE', value: "CORP_MOBILE", label: "法人代表联系号码", orderCode: 32, code: 'order', property: "companyAttr" },
    // {flag:'CURRENT_DEPOSIT', value: 'CURRENT_DEPOSIT', label: '活期存款标志', orderCode: 33, },
    // {flag:'FIXED_DEPOSIT', value: 'FIXED_DEPOSIT', label: '定期存款', orderCode: 34, },
    // {flag:'FINANCIAL_EXPRESS', value: 'FINANCIAL_EXPRESS', label: '财运通', orderCode: 35,},
    // {flag:'CHARACTERISTICS_OF_SAVINGS', value: 'CHARACTERISTICS_OF_SAVINGS', label: '特色储蓄', orderCode: 36, },
    // {flag:'FINANC_BAL', value: 'FINANC_BAL', label: '理财余额', orderCode: 37, isCheck: true, property:"mattersAttr" },
    // {flag:'SMALL_BOOK_LOAN', value: 'SMALL_BOOK_LOAN', label: '小本贷款', orderCode: 38 },
    // {flag:'ORDINARY_LOAN', value: 'ORDINARY_LOAN', label: '普通贷款', orderCode: 39 },
    // {flag:'CONSUMER_LOAN', value: 'CONSUMER_LOAN', label: '消费贷款', orderCode: 40 },
    // {flag:'SELF_HELP_LOAN', value: 'SELF_HELP_LOAN', label: '自助类贷款', orderCode: 40 },
    // {flag:'BUSINESS_WINS_EASY_LOANS', value: 'BUSINESS_WINS_EASY_LOANS', label: '商赢易贷', orderCode: 41 },
    // {flag:'QUICK_AND_EASY_LOAN', value: 'QUICK_AND_EASY_LOAN', label: '快易贷', orderCode: 42 },
    // {flag:'', value: 'EASY_CREDIT_LOAN', label: '信用易贷', orderCode: 43 },
    // {flag:'', value: 'BY_CARD', label: '兴农卡', orderCode: 44 },
    // {flag:'', value: 'SELEF_HELP_CONSUMER_LOAN', label: '自助类消费贷款', orderCode: 45 },
    // {flag:'', value: 'HOUSING_LOAN', label: '安居贷', orderCode: 46 },
    // {flag:'', value: 'SALARY_LOAN', label: '薪金贷', orderCode: 47 },
    // {flag:'', value: 'SALARY_EASY_LOAN', label: '薪易贷', orderCode: 48 },
    // {flag:'', value: 'CHANG_EASY_LOAN', label: '畅易贷', orderCode: 49 },
    // {flag:'', value: 'SALARY_CONSUMPTION', label: '薪消费', orderCode: 50 },
    // {flag:'', value: 'HOUSING_MORTGAGE_LOAN', label: '房易贷', orderCode: 51 },
    { flag: 'CREDIT_LMT', value: 'OVERDRAFT_CREDIT_LMT', label: '信用卡', orderCode: 52, property: "creditAttr" },
    // {flag:'', value: 'ACCEPTANCE', label: '承兑', orderCode: 53,  property:"acceptAttr" },
    // {flag:'', value: 'MORTGAGE_LOANS', label: '按揭贷款', orderCode: 54 },
    // {flag:'', value: 'EFINANCIALCARD', label: 'E融卡', orderCode: 55, },
    // {flag:'', value: 'INTEGRALCARD', label: '积分卡', orderCode: 56, property:"pointAttr" },
    // {flag:'', value: 'ONLINEBANK', label: '网上银行', orderCode: 57, },
    // {flag:'', value: 'WECHATBANK', label: '微信银行', orderCode: 58, },
    { flag: 'SAV_BAL', value: 'SAV_BAL', label: '存款余额', orderCode: 59, isCheck: true, isDisabled: true, property: "saveAttr", isDisplay: '1' },
    { flag: 'M_SAV_AVG', value: 'M_SAV_AVG', label: '存款本月日均', orderCode: 60, isCheck: true, property: "saveAttr", isDisplay: '2' },
    { flag: 'LM_SAV_AVG', value: 'LM_SAV_AVG', label: '存款上月日均', orderCode: 61, property: "saveAttr", isDisplay: '3' },
    { flag: 'Y_SAV_AVG', value: 'Y_SAV_AVG', label: '存款本年日均', orderCode: 62, property: "saveAttr", isDisplay: '4' },
    { flag: 'LY_SAV_AVG', value: 'LY_SAV_AVG', label: '存款上年日均', orderCode: 63, property: "saveAttr", isDisplay: '5' },
    { flag: 'SIXM_SAV_AVG', value: 'SIXM_SAV_AVG', label: '存款前六个月日均', orderCode: 64, property: "saveAttr", isDisplay: '6' },
    // {flag:'', value: 'RESAV_BAL', label: '定期存款余额', orderCode: 65, },
    // {flag:'', value: 'M_RESAV_AVG', label: '定期存款本月日均', orderCode: 66, },
    // {flag:'', value: 'LM_RESAV_AVG', label: '定期存款上月日均', orderCode: 67, },
    // {flag:'', value: 'Y_RESAV_AVG', label: '定期存款本年日均', orderCode: 68, },
    // {flag:'', value: 'LY_RESAV_AVG', label: '定期存款上年日均', orderCode: 69, },
    // {flag:'', value: 'SIXM_RESAV_AVG', label: '定期存款前六个月日均', orderCode: 70, },
    // {flag:'', value: 'CURSAV_BAL', label: '活期存款余额', orderCode: 71, },
    // {flag:'', value: 'M_CURSAV_AVG', label: '活期存款本月日均', orderCode: 72, },
    // {flag:'', value: 'LM_CURSAV_AVG', label: '活期存款上月日均', orderCode: 73, },
    // {flag:'', value: 'Y_CURSAV_AVG', label: '活期存款本年日均', orderCode: 74, },
    // {flag:'', value: 'LY_CURSAV_AVG', label: '活期存款上年日均', orderCode: 75, },
    // {flag:'', value: 'SIXM_CURSAV_AVG', label: '活期存款前六个月日均', orderCode: 76, },
    // {flag:'', value: 'CHCS_SAV_BAL', label: '特色储蓄余额', orderCode: 77, },
    // {flag:'', value: 'LM_CHCS_SAV_BAL', label: '特色储蓄上月日均', orderCode: 78, },
    // {flag:'', value: 'COMP_CRDT_LMT', label: '综合授信授信额度', orderCode: 89 },
    { flag: 'CRED_AMT', value: 'CRED_AMT', label: '授信金额', orderCode: 90, isCheck: true, property: "loansAttr", isDisplay: '1' },
    // {flag:'', value: 'MAX_LOAN_AMT', label: '贷款历史最高贷款金额', orderCode: 91 },
    // {flag:'', value: 'SUM_LOAN_AMT', label: '贷款累计贷款金额', orderCode: 92 },
    { flag: 'LOAN_BAL', value: 'LOAN_BAL', label: '贷款余额', orderCode: 93, isCheck: true, isDisabled: true, property: "loansAttr", isDisplay: '2' },
    { flag: 'M_AVG_BAL', value: 'M_AVG_BAL', label: '贷款本月日均', orderCode: 94, property: "loansAttr", isDisplay: '3' },
    { flag: 'LM_AVG_BAL', value: 'LM_AVG_BAL', label: '贷款上月日均', orderCode: 95, property: "loansAttr", isDisplay: '4' },
    // {flag:'', value: 'Y_LOAN_AVG', label: '贷款本年日均', orderCode: 96, property:"loansAttr", isDisplay:'1' },
    // {flag:'', value: 'LY_LOAN_AVG', label: '贷款上年日均', orderCode: 97,  property:"loansAttr", isDisplay:'1},
    { flag: 'LSIXM_AVG_BAL', value: 'LSIXM_AVG_BAL', label: '贷款前六个月日均', orderCode: 156, property: "loansAttr", isDisplay: '5', },
    // {flag:'', value: 'ORDINARY_LOAN_BAL', label: '普通贷款余额', orderCode: 98 },
    // {flag:'', value: 'ORDINARY_LOAN_AMT', label: '普通贷款金额', orderCode: 99 },
    // {flag:'', value: 'SM_BOOK_LOAN_BAL', label: '小本贷款余额', orderCode: 100 },
    // {flag:'', value: 'SM_BOOK_LOAN_AMT', label: '小本贷款金额', orderCode: 101 },
    // {flag:'', value: 'CONSUMER_LOAN_BAL', label: '消费贷款余额', orderCode: 102 },
    // {flag:'', value: 'CONSUMER_LOAN_AMT', label: '消费贷款金额', orderCode: 103 },
    // {flag:'', value: 'SELF_LOAN_CRDT_LMT', label: '自助类贷款授信额度', orderCode: 104 },
    // {flag:'', value: 'SELF_LOAN_BAL', label: '自助类贷款余额', orderCode: 105 },
    // {flag:'', value: 'SELF_LOAN_AMT', label: '自助类贷款金额', orderCode: 106 },
    // {flag:'', value: 'BWE_LOAN_CRDT_LMT', label: '商赢易贷授信额度', orderCode: 107 },
    // {flag:'', value: 'BWE_LOAN_BAL', label: '商赢易贷余额', orderCode: 108 },
    // {flag:'', value: 'BWE_LOAN_AMT', label: '商赢易贷金额', orderCode: 109 },
    // {flag:'', value: 'BWE_LOAN_ENT_CNT', label: '商赢易贷入账次数', orderCode: 110 },
    // {flag:'', value: 'QE_LOAN_CRDT_LMT', label: '快易贷授信额度', orderCode: 111 },
    // {flag:'', value: 'QE_LOAN_BAL', label: '快易贷余额', orderCode: 112 },
    // {flag:'', value: 'QE_LOAN_AMT', label: '快易贷金额', orderCode: 113 },
    // {flag:'', value: 'QE_LOAN_ENT_CNT', label: '快易贷入账次数', orderCode: 114 },
    // {flag:'', value: 'ECRDT_LOAN_CRDT_LMT', label: '信用易贷授信额度', orderCode: 115 },
    // {flag:'', value: 'ECRDT_LOAN_BAL', label: '信用易贷余额', orderCode: 116 },
    // {flag:'', value: 'ECRDT_LOAN_AMT', label: '信用易贷金额', orderCode: 117 },
    // {flag:'', value: 'ECRDT_LOAN_ENT_CNT', label: '信用易贷入账次数', orderCode: 118 },
    // {flag:'', value: 'BYCARD_CRDT_LMT', label: '兴农卡授信额度', orderCode: 119 },
    // {flag:'', value: 'BYCARD_BAL', label: '兴农卡余额', orderCode: 120 },
    // {flag:'', value: 'BYCARD_AMT', label: '兴农卡金额', orderCode: 121 },
    // {flag:'', value: 'BYCARD_ENT_CNT', label: '兴农卡入账次数', orderCode: 122 },
    // {flag:'', value: 'HOUS_LOAN_BAL', label: '安居贷余额', orderCode: 123 },
    // {flag:'', value: 'HOUS_LOAN_AMT', label: '安居贷金额', orderCode: 124 },
    // {flag:'', value: 'HOUS_MOGA_LOAN_BAL', label: '房易贷余额', orderCode: 125 },
    // {flag:'', value: 'HOUS_MOGA_LOAN_AMT', label: '房易贷金额', orderCode: 126 },
    // {flag:'', value: 'SALARY_CONSUMPTION_BAL', label: '薪消费余额', orderCode: 127 },
    // {flag:'', value: 'SALARY_CONSUMPTION_AMT', label: '薪消费金额', orderCode: 128 },
    // {flag:'', value: 'SALARY_LOAN_CRDT_LMT', label: '薪金贷授信额度', orderCode: 129 },
    // {flag:'', value: 'SALARY_LOAN_BAL', label: '薪金贷余额', orderCode: 130 },
    // {flag:'', value: 'SALARY_LOAN_AMT', label: '薪金贷金额', orderCode: 131 },
    // {flag:'', value: 'SALARY_LOAN_ENT_CNT', label: '薪金贷入账次数', orderCode: 132 },
    // {flag:'', value: 'SALAEASY_LOAN_CRDT_LMT', label: '薪易贷授信额度', orderCode: 133 },
    // {flag:'', value: 'SALAEASY_LOAN_BAL', label: '薪易贷余额', orderCode: 134 },
    // {flag:'', value: 'SALAEASY_LOAN_AMT', label: '薪易贷金额', orderCode: 135 },
    // {flag:'', value: 'SALAEASY_LOAN_ENT_CNT', label: '薪易贷入账次数', orderCode: 136 },
    // {flag:'', value: 'CHEASY_LOAN_BAL', label: '畅易贷余额', orderCode: 137 },
    // {flag:'', value: 'CHEASY_LOAN_AMT', label: '畅易贷金额', orderCode: 138 },
    // {flag:'', value: 'MORTGAGE_LOANS_BAL', label: '按揭贷余额', orderCode: 139 },
    // {flag:'', value: 'MORTGAGE_LOANS_AMOT', label: '按揭贷金额', orderCode: 140 },
    // {flag:'', value: 'E_FINAL_CARD_BAL', label: 'E融卡余额', orderCode: 141 },
    // {flag:'', value: 'E_FINAL_CARD_AMT', label: 'E融卡金额', orderCode: 142 },
    { flag: 'E_IMPAWN_CRED_AMT', value: 'E_IMPAWN_CRED_AMT', label: '承兑金额', orderCode: 143, property: "acceptAttr" },
    { flag: 'E_IMPAWN_M_AVG_BAL', value: 'E_IMPAWN_M_AVG_BAL', label: '承兑敞口', orderCode: 144, property: "acceptAttr" },
    { flag: 'E_IMPAWN_LOAN_BAL', value: 'E_IMPAWN_LOAN_BAL', label: '承兑敞口(余额)', orderCode: 145, property: "acceptAttr" },
    { flag: 'CREAIT_CARD_CRDT_LMT', value: 'CREAIT_CARD_CRDT_LMT', label: '信用卡授信额度', orderCode: 146, property: "creditAttr" },
    { flag: 'OVERDRAFT_CREDIT_LMT', value: 'OVERDRAFT_CREDIT_LMT', label: '信用卡透支余额', orderCode: 147, property: "creditAttr", isCheck: true, isDisabled: true },
    { flag: 'OVDUE_CREDIT_AMT', value: 'OVDUE_CREDIT_AMT', label: '信用卡逾期金额', orderCode: 152, property: "creditAttr", },
    { flag: 'CARD_NUM', value: 'CARD_NUM', label: '信用卡张数', orderCode: 153, property: "creditAttr", },
    { flag: 'INTEGRAL_NUM', value: 'INTEGRAL_NUM', label: '积分卡张数', orderCode: 154, property: "pointAttr", },
    { flag: 'INTEGRAL_BAL', value: 'INTEGRAL_BAL', label: '积分余额', orderCode: 155, property: "pointAttr", },
    // {flag:'WX_Attr', value: 'WX_Attr', label: '持有标识', orderCode: 164, property: "WX_Attr", },
    // {flag:'phoneAttr', value: 'phoneAttr', label: '持有标识', orderCode: 165, property: "phoneAttr", },
    // {flag:'onlineAttr', value: 'onlineAttr', label: '持有标识', orderCode: 166, property: "onlineAttr", },
    { flag: 'PROD_NAME', value: "PROD_NAME", label: "持有产品", orderCode: 167, code: 'order', property: "generalAttr" },
];
var InfoList = [
    // 存款类
    { value: 'SAV_BAL', label: '存款', productId: "C_C_10006", catelgory: "1", property: "saveAttr" },
    { value: 'M_SAV_AVG', label: '存款本月日均', productId: "C_C_10006", catelgory: "2", property: "saveAttr" },
    { value: 'LM_SAV_AVG', label: '存款上月日均', productId: "C_C_10006", catelgory: "3", property: "saveAttr" },
    { value: 'Y_SAV_AVG', label: '存款本年日均', productId: "C_C_10006", catelgory: "4", property: "saveAttr" },
    { value: 'LY_SAV_AVG', label: '存款上年日均', productId: "C_C_10006", catelgory: "5", property: "saveAttr" },
    { value: 'SIXM_SAV_AVG', label: '存款前六个月日均', productId: "C_C_10006", catelgory: "6", property: "saveAttr" },
    // 财运通
    { value: "FIN_EXPRESS_BAL", label: "财运通", productId: "P02001000100001", catelgory: "1", proprety: "saveAttr" },
    { value: "M_FIN_EXPRESS_AVG", label: "财运通本月日均", productId: "P02001000100001", catelgory: "2", proprety: "saveAttr" },
    { value: "LM_FIN_EXPRESS_AVG", label: "财运通上月日均", productId: "P02001000100001", catelgory: "3", proprety: "saveAttr" },
    { value: "Y_FIN_EXPRESS_AVG", label: "财运通本年日均", productId: "P02001000100001", catelgory: "4", proprety: "saveAttr" },
    { value: "LY_FIN_EXPRESS_AVG", label: "财运通上年日均", productId: "P02001000100001", catelgory: "5", proprety: "saveAttr" },
    { value: "SIXM_FIN_EXPRESS_AVG", label: "财运通前六个月日均", productId: "P02001000100001", catelgory: "6", proprety: "saveAttr" },
    // 小额财运通
    { value: "SMA_FIN_EXPR_BAL", label: "小额财运通", productId: "P02001000100002", catelgory: "1", proprety: "saveAttr" },
    { value: "M_SMA_FIN_EXPR_AVG", label: "小额财运通本月日均", productId: "P02001000100002", catelgory: "2", proprety: "saveAttr" },
    { value: "LM_SMA_FIN_EXPR_AVG", label: "小额财运通上月日均", productId: "P02001000100002", catelgory: "3", proprety: "saveAttr" },
    { value: "Y_SMA_FIN_EXPR_AVG", label: "小额财运通本年日均", productId: "P02001000100002", catelgory: "4", proprety: "saveAttr" },
    { value: "LY_SMA_FIN_EXPR_AVG", label: "小额财运通上年日均", productId: "P02001000100002", catelgory: "5", proprety: "saveAttr" },
    { value: "SIXM_SMA_FIN_EXPR_AVG", label: "小额财运通前六个月日均", productId: "P02001000100002", catelgory: "6", proprety: "saveAttr" },
    // 特色储蓄
    { value: "CHCS_SAV_BAL", label: "特色储蓄", productId: "P02001000100003", catelgory: "1", proprety: "saveAttr" },
    { value: "M_CHCS_SAV_AVG", label: "特色储蓄本月日均", productId: "P02001000100003", catelgory: "2", proprety: "saveAttr" },
    { value: "LM_CHCS_SAV_AVG", label: "特色储蓄上月日均", productId: "P02001000100003", catelgory: "3", proprety: "saveAttr" },
    { value: "Y_CHCS_SAV_AVG", label: "特色储蓄本年日均", productId: "P02001000100003", catelgory: "4", proprety: "saveAttr" },
    { value: "LY_CHCS_SAV_AVG", label: "特色储蓄上年日均", productId: "P02001000100003", catelgory: "5", proprety: "saveAttr" },
    { value: "SIXM_CHCS_SAV_AVG", label: "特色储蓄前六个月日均", productId: "P02001000100003", catelgory: "6", proprety: "saveAttr" },
    // 大额存单
    { value: "CER_DEPO_BAL", label: "大额存单", productId: "P02001000100004", catelgory: "1", proprety: "saveAttr" },
    { value: "M_CER_DEPO_AVG", label: "大额存单本月日均", productId: "P02001000100004", catelgory: "2", proprety: "saveAttr" },
    { value: "LM_CER_DEPO_AVG", label: "大额存单上月日均", productId: "P02001000100004", catelgory: "3", proprety: "saveAttr" },
    { value: "Y_CER_DEPO_AVG", label: "大额存单本年日均", productId: "P02001000100004", catelgory: "4", proprety: "saveAttr" },
    { value: "LY_CER_DEPO_AVG", label: "大额存单上年日均", productId: "P02001000100004", catelgory: "5", proprety: "saveAttr" },
    { value: "SIXM_CER_DEPO_AVG", label: "大额存单前六个月日均", productId: "P02001000100004", catelgory: "6", proprety: "saveAttr" },
    // 个人活期
    { value: "PERS_CURR_BAL", label: "个人活期", productId: "P02001000100005", catelgory: "1", proprety: "saveAttr" },
    { value: "M_PERS_CURR_AVG", label: "个人活期本月日均", productId: "P02001000100005", catelgory: "2", proprety: "saveAttr" },
    { value: "LM_PERS_CURR_AVG", label: "个人活期上月日均", productId: "P02001000100005", catelgory: "3", proprety: "saveAttr" },
    { value: "Y_PERS_CURR_AVG", label: "个人活期本年日均", productId: "P02001000100005", catelgory: "4", proprety: "saveAttr" },
    { value: "LY_PERS_CURR_AVG", label: "个人活期上年日均", productId: "P02001000100005", catelgory: "5", proprety: "saveAttr" },
    { value: "SIXM_PERS_CURR_AVG", label: "个人活期前六个月日均", productId: "P02001000100005", catelgory: "6", proprety: "saveAttr" },
    // 个人其他
    { value: "PERS_OTHER_BAL", label: "个人其他", productId: "P02001000100006", catelgory: "1", proprety: "saveAttr" },
    { value: "M_PERS_OTHER_AVG", label: "个人其他本月日均", productId: "P02001000100006", catelgory: "2", proprety: "saveAttr" },
    { value: "LM_PERS_OTHER_AVG", label: "个人其他上月日均", productId: "P02001000100006", catelgory: "3", proprety: "saveAttr" },
    { value: "Y_PERS_OTHER_AVG", label: "个人其他本年日均", productId: "P02001000100006", catelgory: "4", proprety: "saveAttr" },
    { value: "LY_PERS_OTHER_AVG", label: "个人其他上年日均", productId: "P02001000100006", catelgory: "5", proprety: "saveAttr" },
    { value: "SIXM_PERS_OTHER_AVG", label: "个人其他前六个月日均", productId: "P02001000100006", catelgory: "6", proprety: "saveAttr" },
    // 单位活期
    { value: "UNIT_CURR_BAL", label: "单位活期", productId: "P02001000100007", catelgory: "1", proprety: "saveAttr" },
    { value: "M_UNIT_CURR_AVG", label: "单位活期本月日均", productId: "P02001000100007", catelgory: "2", proprety: "saveAttr" },
    { value: "LM_UNIT_CURR_AVG", label: "单位活期上月日均", productId: "P02001000100007", catelgory: "3", proprety: "saveAttr" },
    { value: "Y_UNIT_CURR_AVG", label: "单位活期本年日均", productId: "P02001000100007", catelgory: "4", proprety: "saveAttr" },
    { value: "LY_UNIT_CURR_AVG", label: "单位活期上年日均", productId: "P02001000100007", catelgory: "5", proprety: "saveAttr" },
    { value: "SIXM_UNIT_CURR_AVG", label: "单位活期前六个月日均", productId: "P02001000100007", catelgory: "6", proprety: "saveAttr" },
    // 单位其他
    { value: "UNIT_OTHER_BAL", label: "单位其他", productId: "P02001000100008", catelgory: "1", proprety: "saveAttr" },
    { value: "M_UNIT_OTHER_AVG", label: "单位其他本月日均", productId: "P02001000100008", catelgory: "2", proprety: "saveAttr" },
    { value: "LM_UNIT_OTHER_AVG", label: "单位其他上月日均", productId: "P02001000100008", catelgory: "3", proprety: "saveAttr" },
    { value: "Y_UNIT_OTHER_AVG", label: "单位其他本年日均", productId: "P02001000100008", catelgory: "4", proprety: "saveAttr" },
    { value: "LY_UNIT_OTHER_AVG", label: "单位其他上年日均", productId: "P02001000100008", catelgory: "5", proprety: "saveAttr" },
    { value: "SIXM_UNIT_OTHER_AVG", label: "单位其他前六个月日均", productId: "P02001000100008", catelgory: "6", proprety: "saveAttr" },
    // 保证金存款
    { value: "BOND_DEPO_BAL", label: "保证金存款", productId: "P02001000100009", catelgory: "1", proprety: "saveAttr" },
    { value: "M_BOND_DEPO_AVG", label: "保证金存款本月日均", productId: "P02001000100009", catelgory: "2", proprety: "saveAttr" },
    { value: "LM_BOND_DEPO_AVG", label: "保证金存款上月日均", productId: "P02001000100009", catelgory: "3", proprety: "saveAttr" },
    { value: "Y_BOND_DEPO_AVG", label: "保证金存款本年日均", productId: "P02001000100009", catelgory: "4", proprety: "saveAttr" },
    { value: "LY_BOND_DEPO_AVG", label: "保证金存款上年日均", productId: "P02001000100009", catelgory: "5", proprety: "saveAttr" },
    { value: "SIXM_BOND_DEPO_AVG", label: "保证金存款前六个月日均", productId: "P02001000100009", catelgory: "6", proprety: "saveAttr" },
    // 其他存款
    { value: "OTHER_DEPO_BAL", label: "其他存款", productId: "P02001000100010", catelgory: "1", proprety: "saveAttr" },
    { value: "M_OTHER_DEPO_AVG", label: "其他存款本月日均", productId: "P02001000100010", catelgory: "2", proprety: "saveAttr" },
    { value: "LM_OTHER_DEPO_AVG", label: "其他存款上月日均", productId: "P02001000100010", catelgory: "3", proprety: "saveAttr" },
    { value: "Y_OTHER_DEPO_AVG", label: "其他存款本年日均", productId: "P02001000100010", catelgory: "4", proprety: "saveAttr" },
    { value: "LY_OTHER_DEPO_AVG", label: "其他存款上年日均", productId: "P02001000100010", catelgory: "5", proprety: "saveAttr" },
    { value: "SIXM_OTHER_DEPO_AVG", label: "其他存款前六个月日均", productId: "P02001000100010", catelgory: "6", proprety: "saveAttr" },
    // 贷款类
    // 按揭贷款
    { value: "MORTGAGE_CRED_AMT", label: "按揭贷款授信金额", productId: "C_C_10023", property: "loansAttr", catelgory: "1" },
    { value: "MORTGAGE_LOAN_BAL", label: "按揭贷款贷款余额", productId: "C_C_10023", property: "loansAttr", catelgory: "2" },
    { value: "MORTGAGE_M_AVG_BAL", label: "按揭贷款贷款本月日均", productId: "C_C_10023", property: "loansAttr", catelgory: "3" },
    { value: "MORTGAGE_LM_AVG_BAL", label: "按揭贷款贷款上月日均", productId: "C_C_10023", property: "loansAttr", catelgory: "4" },
    { value: "MORTGAGE_LSIXM_AVG_BAL", label: "按揭贷款贷款前六个月日均", productId: "C_C_10023", property: "loansAttr", catelgory: "5" },
    // 普通贷款
    { value: "ORDLOAN_CRED_AMT", label: "普通贷款授信金额", productId: "C_C_10015", property: "loansAttr", catelgory: "1" },
    { value: "ORDLOAN_LOAN_BAL", label: "普通贷款贷款余额", productId: "C_C_10015", property: "loansAttr", catelgory: "2" },
    { value: "ORDLOAN_M_AVG_BAL", label: "普通贷款贷款本月日均", productId: "C_C_10015", property: "loansAttr", catelgory: "3" },
    { value: "ORDLOAN_LM_AVG_BAL", label: "普通贷款贷款上月日均", productId: "C_C_10015", property: "loansAttr", catelgory: "4" },
    { value: "ORDLOAN_LSIXM_AVG_BAL", label: "普通贷款贷款前六个月日均", productId: "C_C_10015", property: "loansAttr", catelgory: "5" },
    // 小本贷款
    { value: "SMBOOK_CRED_AMT", label: "小本贷款授信金额", productId: "C_C_10018", property: "loansAttr", catelgory: "1" },
    { value: "SMBOOK_LOAN_BAL", label: "小本贷款贷款余额", productId: "C_C_10018", property: "loansAttr", catelgory: "2" },
    { value: "SMBOOK_M_AVG_BAL", label: "小本贷款贷款本月日均", productId: "C_C_10018", property: "loansAttr", catelgory: "3" },
    { value: "SMBOOK_LM_AVG_BAL", label: "小本贷款贷款上月日均", productId: "C_C_10018", property: "loansAttr", catelgory: "4" },
    { value: "SMBOOK_LSIXM_AVG_BAL", label: "小本贷款贷款前六个月日均", productId: "C_C_10018", property: "loansAttr", catelgory: "5" },
    // 一般小本贷款
    { value: "GENSMAL_CRED_AMT", label: "一般小本贷款授信金额", productId: "P01002000200012", property: "loansAttr", catelgory: "1" },
    { value: "GENSMAL_LOAN_BAL", label: "一般小本贷款贷款余额", productId: "P01002000200012", property: "loansAttr", catelgory: "2" },
    // 青年置业贷款
    { value: "YOUNGPUR_CRED_AMT", label: "青年置业贷款授信金额", productId: "P01002000701004", property: "loansAttr", catelgory: "1" },
    { value: "YOUNGPUR_LOAN_BAL", label: "青年置业贷款贷款余额", productId: "P01002000701004", property: "loansAttr", catelgory: "2" },
    // 小本易租贷
    { value: "SMCDEASY_CRED_AMT", label: "小本易租贷贷款授信金额", productId: "P23001000100015", property: "loansAttr", catelgory: "1" },
    { value: "SMCDEASY_LOAN_BAL", label: "小本易租贷贷款贷款余额", productId: "P23001000100015", property: "loansAttr", catelgory: "2" },
    // 小本自助贷款
    { value: "SMCDSELF_CRED_AMT", label: "小本自助贷款授信金额", productId: "P23001000100016", property: "loansAttr", catelgory: "1" },
    { value: "SMCDSELF_LOAN_BAL", label: "小本自助贷款贷款余额", productId: "P23001000100016", property: "loansAttr", catelgory: "2" },
    // 兴农贷
    { value: "BYLOAN_CRED_AMT", label: "兴农贷授信金额", productId: "P23001000100017", property: "loansAttr", catelgory: "1" },
    { value: "BYLOAN_LOAN_BAL", label: "兴农贷贷款余额", productId: "P23001000100017", property: "loansAttr", catelgory: "2" },
    // 自助类贷款
    { value: "SELFTYPE_CRED_AMT", label: "自助类贷款授信金额", productId: "C_C_10016", property: "loansAttr", catelgory: "1" },
    { value: "SELFTYPE_LOAN_BAL", label: "自助类贷款贷款余额", productId: "C_C_10016", property: "loansAttr", catelgory: "2" },
    { value: "SELFTYPE_M_AVG_BAL", label: "自助类贷款贷款本月日均", productId: "C_C_10016", property: "loansAttr", catelgory: "3" },
    { value: "SELFTYPE_LM_AVG_BAL", label: "自助类贷款贷款上月日均", productId: "C_C_10016", property: "loansAttr", catelgory: "4" },
    { value: "SELFTYPE_LSIXM_AVG_BAL", label: "自助类贷款贷款前六个月日均", productId: "C_C_10016", property: "loansAttr", catelgory: "5" },
    // 自助贷款
    { value: "SELF_CRED_AMT", label: "自助贷款授信金额", productId: "P01001000200006", property: "loansAttr", catelgory: "1" },
    { value: "SELF_LOAN_BAL", label: "自助贷款贷款余额", productId: "P01001000200006", property: "loansAttr", catelgory: "2" },
    // 信用易贷
    { value: "ECRDT_CRED_AMT", label: "信用易贷授信金额", productId: "P01001000200005", property: "loansAttr", catelgory: "1" },
    { value: "ECRDT_LOAN_BAL", label: "信用易贷贷款余额", productId: "P01001000200005", property: "loansAttr", catelgory: "2" },
    // 快易贷
    { value: "QE_CRED_AMT", label: "快易贷授信金额", productId: "P01001000200001", property: "loansAttr", catelgory: "1" },
    { value: "QE_LOAN_BAL", label: "快易贷贷款余额", productId: "P01001000200001", property: "loansAttr", catelgory: "2" },
    // 商赢·易贷
    { value: "BWE_CRED_AMT", label: "商赢·易贷授信金额", productId: "P01001000200002", property: "loansAttr", catelgory: "1" },
    { value: "BWE_LOAN_BAL", label: "商赢·易贷贷款余额", productId: "P01001000200002", property: "loansAttr", catelgory: "2" },
    // 分期类贷款
    { value: "INSTLOAN_CRED_AMT", label: "分期类贷款授信金额", productId: "C_C_10017", property: "loansAttr", catelgory: "1" },
    { value: "INSTLOAN_LOAN_BAL", label: "分期类贷款贷款余额", productId: "C_C_10017", property: "loansAttr", catelgory: "2" },
    { value: "INSTLOAN_M_AVG_BAL", label: "分期类贷款贷款本月日均", productId: "C_C_10017", property: "loansAttr", catelgory: "3" },
    { value: "INSTLOAN_LM_AVG_BAL", label: "分期类贷款贷款上月日均", productId: "C_C_10017", property: "loansAttr", catelgory: "4" },
    { value: "INSTLOAN_LSIXM_AVG_BAL", label: "分期类贷款贷款前六个月日均", productId: "C_C_10017", property: "loansAttr", catelgory: "5" },
    // 畅易贷
    { value: "CHEASY_CRED_AMT", label: "畅易贷授信金额", productId: "P01002000200009", property: "loansAttr", catelgory: "1" },
    { value: "CHEASY_LOAN_BAL", label: "畅易贷贷款余额", productId: "P01002000200009", property: "loansAttr", catelgory: "2" },
    // E融卡
    { value: "E_FINAL_CRED_AMT", label: "E融卡贷款授信金额", productId: "C_C_10019", property: "loansAttr", catelgory: "1" },
    { value: "E_FINAL_LOAN_BAL", label: "E融卡贷款贷款余额", productId: "C_C_10019", property: "loansAttr", catelgory: "2" },
    { value: "E_FINAL_M_AVG_BAL", label: "E融卡贷款贷款本月日均", productId: "C_C_10019", property: "loansAttr", catelgory: "3" },
    { value: "E_FINAL_LM_AVG_BAL", label: "E融卡贷款贷款上月日均", productId: "C_C_10019", property: "loansAttr", catelgory: "4" },
    { value: "E_FINAL_LSIXM_AVG_BAL", label: "E融卡贷款贷款前六个月日均", productId: "C_C_10019", property: "loansAttr", catelgory: "5" },
    // 自助卡
    { value: "SELFCARD_CRED_AMT", label: "自助卡贷款授信金额", productId: "C_C_10020", property: "loansAttr", catelgory: "1" },
    { value: "SELFCARD_LOAN_BAL", label: "自助卡贷款贷款余额", productId: "C_C_10020", property: "loansAttr", catelgory: "2" },
    { value: "SELFCARD_M_AVG_BAL", label: "自助卡贷款贷款本月日均", productId: "C_C_10020", property: "loansAttr", catelgory: "3" },
    { value: "SELFCARD_LM_AVG_BAL", label: "自助卡贷款贷款上月日均", productId: "C_C_10020", property: "loansAttr", catelgory: "4" },
    { value: "SELFCARD_LSIXM_AVG_BAL", label: "自助卡贷款贷款前六个月日均", productId: "C_C_10020", property: "loansAttr", catelgory: "5" },
    // 村聚易贷·兴农卡
    { value: "BYCARD_CRED_AMT", label: "村聚易贷·兴农卡授信金额", productId: "P01001000100001", property: "loansAttr", catelgory: "1" },
    { value: "BYCARD_LOAN_BAL", label: "村聚易贷·兴农卡贷款余额", productId: "P01001000100001", property: "loansAttr", catelgory: "2" },
    // 兴福卡
    { value: "XINGF_CRED_AMT", label: "兴福卡授信金额", productId: "P01001000100003", property: "loansAttr", catelgory: "1" },
    { value: "XINGF_LOAN_BAL", label: "兴福卡贷款余额", productId: "P01001000100003", property: "loansAttr", catelgory: "2" },
    // 存贷合一卡
    { value: "DEAN_IN_CRED_AMT", label: "存贷合一卡授信金额", productId: "P01001000100002", property: "loansAttr", catelgory: "1" },
    { value: "DEAN_IN_LOAN_BAL", label: "存贷合一卡贷款余额", productId: "P01001000100002", property: "loansAttr", catelgory: "2" },
    // 消费贷款
    { value: "CONSUMER_CRED_AMT", label: "消费贷款贷款授信金额", productId: "C_C_10021", property: "loansAttr", catelgory: "1" },
    { value: "CONSUMER_LOAN_BAL", label: "消费贷款贷款贷款余额", productId: "C_C_10021", property: "loansAttr", catelgory: "2" },
    { value: "CONSUMER_M_AVG_BAL", label: "消费贷款贷款贷款本月日均", productId: "C_C_10021", property: "loansAttr", catelgory: "3" },
    { value: "CONSUMER_LM_AVG_BAL", label: "消费贷款贷款贷款上月日均", productId: "C_C_10021", property: "loansAttr", catelgory: "4" },
    { value: "CONSUMER_LSIXM_AVG_BAL", label: "消费贷款贷款贷款前六个月日均", productId: "C_C_10021", property: "loansAttr", catelgory: "5" },
    // 安居贷
    { value: "BYCARD_CRED_AMT", label: "安居贷授信金额", productId: "P01002000200005", property: "loansAttr", catelgory: "1" },
    { value: "BYCARD_LOAN_BAL", label: "安居贷贷款余额", productId: "P01002000200005", property: "loansAttr", catelgory: "2" },
    // 薪金贷
    { value: "BYCARD_CRED_AMT", label: "薪金贷授信金额", productId: "P01001000200003", property: "loansAttr", catelgory: "1" },
    { value: "BYCARD_LOAN_BAL", label: "薪金贷贷款余额", productId: "P01001000200003", property: "loansAttr", catelgory: "2" },
    // 薪消费
    { value: "BYCARD_CRED_AMT", label: "薪消费授信金额", productId: "P01002000201006", property: "loansAttr", catelgory: "1" },
    { value: "BYCARD_LOAN_BAL", label: "薪消费贷款余额", productId: "P01002000201006", property: "loansAttr", catelgory: "2" },
    // 房易贷
    { value: "BYCARD_CRED_AMT", label: "房易贷授信金额", productId: "P01002000200010", property: "loansAttr", catelgory: "1" },
    { value: "BYCARD_LOAN_BAL", label: "房易贷贷款余额", productId: "P01002000200010", property: "loansAttr", catelgory: "2" },
    // 薪易贷
    { value: "BYCARD_CRED_AMT", label: "薪易贷授信金额", productId: "P01001000200004", property: "loansAttr", catelgory: "1" },
    { value: "BYCARD_LOAN_BAL", label: "薪易贷贷款余额", productId: "P01001000200004", property: "loansAttr", catelgory: "2" },
    // e质押”自助质押贷
    { value: "E_IMPAWN_CRED_AMT", label: "e质押”自助质押贷授信金额", productId: "C_C_10022", property: "loansAttr", catelgory: "1" },
    { value: "E_IMPAWN_LOAN_BAL", label: "e质押”自助质押贷贷款余额", productId: "C_C_10022", property: "loansAttr", catelgory: "2" },
    { value: "E_IMPAWN_M_AVG_BAL", label: "e质押”自助质押贷贷款本月日均", productId: "C_C_10022", property: "loansAttr", catelgory: "3" },
    { value: "E_IMPAWN_LM_AVG_BAL", label: "e质押”自助质押贷贷款上月日均", productId: "C_C_10022", property: "loansAttr", catelgory: "4" },
    { value: "E_IMPAWN_LSIXM_AVG_BAL", label: "e质押”自助质押贷贷款前六个月日均", productId: "C_C_10022", property: "loansAttr", catelgory: "5" },
    // e质押(个人消费)
    { value: "EI_GR_CRED_AMT", label: "e质押(个人消费)授信金额", productId: "P01001000200007", property: "loansAttr", catelgory: "1" },
    { value: "EI_GR_LOAN_BAL", label: "e质押(个人消费)贷款余额", productId: "P01001000200007", property: "loansAttr", catelgory: "2" },
    // e质押(生产经营)
    { value: "EI_SC_CRED_AMT", label: "e质押(生产经营)授信金额", productId: "P01001000200008", property: "loansAttr", catelgory: "1" },
    { value: "EI_SC_LOAN_BAL", label: "e质押(生产经营)贷款余额", productId: "P01001000200008", property: "loansAttr", catelgory: "2" },
    // 承兑
    { value: "E_IMPAWN_CRED_AMT", label: "承兑金额", productId: "C_C_10008", catelgory: "1" },
    { value: "E_IMPAWN_LOAN_BAL", label: "承兑敞口(余额)", productId: "C_C_10008", catelgory: "2" },
    { value: "E_IMPAWN_M_AVG_BAL", label: "承兑敞口", productId: "C_C_10008", catelgory: "3" },
    // 理财
    { value: "FINANC_BAL", label: "理财余额", productId: "C_C_10009", catelgory: "1" },
    // 信用卡
    { value: "CREAIT_CARD_CRDT_LMT", label: "信用卡授信额度", productId: "C_C_10010", catelgory: "1" },
    { value: "OVERDRAFT_CREDIT_LMT", label: "信用卡透支额度", productId: "C_C_10010", catelgory: "2" },
    { value: "OVDUE_CREDIT_AMT", label: "信用卡逾期金额", productId: "C_C_10010", catelgory: "3" },
    { value: "CARD_NUM", label: "信用卡张数", productId: "C_C_10010", catelgory: "4" },
    // { value: "E_IMPAWN_M_AVG_BAL", label: "开卡日期", productId: "C_C_10010", catelgory: "5" },
    // { value: "E_IMPAWN_M_AVG_BAL", label: "到期日期", productId: "C_C_10010", catelgory: "6" },
    { value: "CARD_NATURE", label: "卡状态", productId: "C_C_10010", catelgory: "7" },
    // 积分卡
    { value: "INTEGRAL_BAL", label: "积分余额", productId: "C_C_10011", catelgory: "1" },
    { value: "INTEGRAL_NUM", label: "积分卡张数", productId: "C_C_10011", catelgory: "2" },
];
var preAppprovedListinfo = [
    { value: 'serialNumber', label: '流水号', isCheck: true, },
    { value: 'custNo', label: '客户号', isCheck: false, },
    { value: 'custName', label: '客户名称', isCheck: false, },
    { value: 'currentContractNo', label: '合同编号', isCheck: false, },
    { value: 'approveDate', label: '合同审批通过日期', isCheck: false, },
    { value: 'loanProperty', label: '贷款性质', isCheck: false, },
    { value: 'custSource', label: '客户来源', isCheck: false },
    { value: 'loanForm', label: '贷款形式', isCheck: false, },
    { value: 'loanType', label: '贷款种类', isCheck: false, },
    { value: 'currentProductName', label: '产品名称', isCheck: false, },
    { value: 'loanPayMethod', label: '贷款支付方式', isCheck: false, },
    { value: 'contactKind', label: '合同种类', isCheck: false, },
    { value: 'contractNum', label: '永续合同号', isCheck: false, },
    { value: 'guaranteeMode', label: '主担保方式', isCheck: false, },
    { value: 'contractMode', label: '主合同方式', isCheck: false, },
    { value: 'guaranteeContractNo', label: '担保合同编号', isCheck: false, },
    { value: 'loanAmt', label: '贷款金额', isCheck: false, },
    // { value: 'contractAmt', label: '合同余额', isCheck: false,}, 
    { value: 'loanDateStart', label: '起贷日期', isCheck: false, },
    { value: 'loanDateEnd', label: '止贷日期', isCheck: false, },
    { value: 'loanLimit', label: '贷款限额', isCheck: false, },
    { value: 'accrualScale', label: '积数比例', isCheck: false, },
    { value: 'loanRate', label: '贷款利率（‰）', isCheck: false, },
    // { value: 'overdueRate', label: '逾期利率（‰）', isCheck: false,},
    // { value: 'compoundInterestRate', label: '复利利率（‰）', isCheck: false,},
    // { value: 'defaultRate', label: '违约利率（‰）', isCheck: false,},
    { value: 'interestMode', label: '计息方式', isCheck: false, },
    { value: 'payType', label: '还款方式', isCheck: false, },
    { value: 'interrstAcctNo', label: '计息账号', isCheck: false, },
    // { value: 'loanPurpuse', label: '贷款用途', isCheck: false,}, 
    { value: 'repayAmtQuarry', label: '还款资金来源', isCheck: false, },
    { value: 'tellerNo', label: '经办人工号', isCheck: false, },
    { value: 'tellerName', label: '经办人名称', isCheck: false, },
    { value: 'tellerOrgNo', label: '经办机构', isCheck: false, },
    { value: 'tellerOrgName', label: '经办机构名称', isCheck: false, },
    { value: 'tellerDate', label: '经办日期', isCheck: false, },
    { value: 'creidtAmt', label: '信用额度', isCheck: false, },
    { value: 'businessStatus', label: '登记簿状态', isCheck: false, }
];


/***/ })

}]);
//# sourceMappingURL=default~advanced-search-advanced-search-module~batch-precredit-add-batch-precredit-add-module~credit~15704ef9.js.map